import type { Language } from "./i18n";

export type OrganId =
  | "heart"
  | "brain"
  | "lungs"
  | "liver"
  | "kidneys"
  | "eyeball"
  | "intestine"
  | "pancreas"
  | "skin";

export type Hotspot = {
  id: string;
  label: string;
  labelRu?: string;
  detail: string;
  detailRu?: string;
  position: [number, number, number];
  color: string;
};

export type Organ = {
  id: OrganId;
  name: string;
  nameRu: string;
  scientificName: string;
  system: string;
  systemRu: string;
  model: string;
  icon: string;
  accent: string;
  description: string;
  descriptionRu: string;
  poetic: string;
  poeticRu: string;
  size: string;
  sizeRu: string;
  weight: string;
  weightRu: string;
  location: string;
  locationRu: string;
  function: string;
  functionRu: string;
  dailyFact: string;
  dailyFactRu: string;
  medical: string;
  medicalRu: string;
  bloodSupply: string;
  bloodSupplyRu: string;
  /** A single memorable line, surfaced as the "Did you know" note. */
  funFact: string;
  funFactRu: string;
  tissue: string;
  tissueRu: string;
  comparison: string;
  comparisonRu: string;
  conditions: string[];
  conditionsRu: string[];
  hotspots: Hotspot[];
  /** Whether `/anatomy/<id>/*.webp` illustrations exist. Organs without them
   *  fall back to the accent glyph rather than a broken image. */
  illustrated: boolean;
};

export const organs: Organ[] = [
  {
    id: "heart",
    name: "Heart",
    nameRu: "Сердце",
    scientificName: "Cor",
    system: "Cardiovascular",
    systemRu: "Сердечно-сосудистая",
    model: "/models/heart.glb",
    icon: "♥",
    accent: "#ee7c6a",
    description: "A muscular organ that pumps blood throughout the body, delivering oxygen and nutrients to every cell.",
    descriptionRu: "Мышечный орган, перекачивающий кровь по всему телу и доставляющий кислород и питательные вещества каждой клетке.",
    poetic: "The tireless pump",
    poeticRu: "Неутомимый насос",
    size: "About the size of your fist",
    sizeRu: "Примерно с ваш кулак",
    weight: "250–350 g",
    weightRu: "250–350 г",
    location: "Behind the sternum, slightly left",
    locationRu: "За грудиной, чуть слева",
    function: "Circulates oxygenated blood",
    functionRu: "Циркуляция обогащенной кислородом крови",
    dailyFact: "Beats about 100,000 times",
    dailyFactRu: "Совершает около 100 000 ударов в день",
    medical: "Its electrical rhythm coordinates every heartbeat.",
    medicalRu: "Электрический ритм координирует каждое сокращение сердца.",
    bloodSupply: "Left and right coronary arteries",
    bloodSupplyRu: "Левая и правая коронарные артерии",
    funFact: "It beats roughly 2.5 billion times in an average lifetime, and starts before you are born.",
    funFactRu: "За жизнь сердце сокращается около 2,5 миллиардов раз, начиная работу еще до вашего рождения.",
    tissue: "Cardiac muscle tissue",
    tissueRu: "Сердечная мышечная ткань",
    comparison: "Heart vs. brain",
    comparisonRu: "Сердце против мозга",
    conditions: ["Coronary artery disease", "Arrhythmia", "Heart valve disorders", "Heart failure", "Cardiomyopathy", "Myocarditis", "Atrial fibrillation", "Congenital heart defects"],
    conditionsRu: ["Ишемическая болезнь сердца", "Аритмия", "Пороки клапанов сердца", "Сердечная недостаточность", "Кардиомиопатия", "Миокардит", "Мерцательная аритмия", "Врожденные пороки сердца"],
    illustrated: true,
    hotspots: [
      { id: "aorta", label: "Aorta", labelRu: "Аорта", detail: "Main artery", detailRu: "Главная артерия", position: [-0.35, 1.65, 0.55], color: "#ee7c6a" },
      { id: "left-atrium", label: "Left Atrium", labelRu: "Левое предсердие", detail: "Receives oxygenated blood", detailRu: "Принимает обогащенную кровь", position: [0.82, 0.65, 0.5], color: "#f2a33b" },
      { id: "right-atrium", label: "Right Atrium", labelRu: "Правое предсердие", detail: "Receives venous blood", detailRu: "Принимает венозную кровь", position: [-0.9, 0.35, 0.55], color: "#6393d8" },
      { id: "left-ventricle", label: "Left Ventricle", labelRu: "Левый желудочек", detail: "Pumps to the body", detailRu: "Качает кровь к органам", position: [0.7, -0.75, 0.65], color: "#f2a33b" },
      { id: "right-ventricle", label: "Right Ventricle", labelRu: "Правый желудочек", detail: "Pumps to the lungs", detailRu: "Качает кровь к легким", position: [-0.65, -0.68, 0.66], color: "#ee7c6a" },
      { id: "mitral", label: "Mitral Valve", labelRu: "Митральный клапан", detail: "Prevents backflow", detailRu: "Предотвращает обратный ток", position: [0.18, -1.35, 0.48], color: "#d89bc4" },
    ],
  },
  {
    id: "brain",
    name: "Brain",
    nameRu: "Головной мозг",
    scientificName: "Encephalon",
    system: "Nervous System",
    systemRu: "Нервная система",
    model: "/models/brain.glb",
    icon: "◉",
    accent: "#c58696",
    description: "The body’s command center, integrating sensation, memory, emotion, and precise movement.",
    descriptionRu: "Командный центр организма, объединяющий ощущения, память, эмоции и точные движения.",
    poetic: "The universe within",
    poeticRu: "Вселенная внутри",
    size: "Roughly two clenched fists",
    sizeRu: "Примерно с два сжатых кулака",
    weight: "1.3–1.4 kg",
    weightRu: "1.3–1.4 кг",
    location: "Protected within the skull",
    locationRu: "Защищен внутри черепа",
    function: "Processes and coordinates signals",
    functionRu: "Обработка и координация сигналов",
    dailyFact: "Uses about 20% of the body’s energy",
    dailyFactRu: "Потребляет около 20% энергии тела",
    medical: "Billions of neurons communicate through electrical and chemical signals.",
    medicalRu: "Миллиарды нейронов передают электрические и химические сигналы.",
    bloodSupply: "Internal carotid and vertebral arteries",
    bloodSupplyRu: "Внутренние сонные и позвоночные артерии",
    funFact: "It has no pain receptors of its own — a headache is felt in the tissues around it.",
    funFactRu: "Сам мозг не имеет болевых рецепторов — головная боль ощущается в окружающих тканях.",
    tissue: "Cerebral cortex",
    tissueRu: "Кора головного мозга",
    comparison: "Brain vs. eye",
    comparisonRu: "Мозг против глаза",
    conditions: ["Migraine", "Stroke", "Neurodegenerative disease", "Epilepsy", "Traumatic brain injury", "Meningitis", "Multiple sclerosis", "Brain aneurysm"],
    conditionsRu: ["Мигрень", "Инсульт", "Нейродегенеративные заболевания", "Эпилепсия", "Черепно-мозговая травма", "Менингит", "Рассеянный склероз", "Аневризма мозга"],
    illustrated: true,
    hotspots: [
      { id: "frontal", label: "Frontal Lobe", labelRu: "Лобная доля", detail: "Planning & movement", detailRu: "Планирование и движения", position: [-0.7, 0.65, 0.8], color: "#ee7c6a" },
      { id: "parietal", label: "Parietal Lobe", labelRu: "Теменная доля", detail: "Sensory integration", detailRu: "Интеграция сенсорных сигналов", position: [0.15, 1.1, 0.65], color: "#f2a33b" },
      { id: "temporal", label: "Temporal Lobe", labelRu: "Височная доля", detail: "Memory & hearing", detailRu: "Память и слух", position: [0.75, -0.1, 0.82], color: "#6393d8" },
      { id: "cerebellum", label: "Cerebellum", labelRu: "Мозжечок", detail: "Balance & coordination", detailRu: "Баланс и координация", position: [0.72, -0.9, 0.55], color: "#d89bc4" },
    ],
  },
  {
    id: "lungs",
    name: "Lungs",
    nameRu: "Легкие",
    scientificName: "Pulmones",
    system: "Respiratory System",
    systemRu: "Дыхательная система",
    model: "/models/lungs.glb",
    icon: "◍",
    accent: "#dd8f8b",
    description: "Paired organs that draw in air and trade oxygen for carbon dioxide across a vast, delicate surface.",
    descriptionRu: "Парные органы, втягивающие воздух и меняющие кислород на углекислый газ через обширную поверхность.",
    poetic: "The breath of life",
    poeticRu: "Дыхание жизни",
    size: "Each about 25 cm tall",
    sizeRu: "Каждое высотой около 25 см",
    weight: "About 1 kg for the pair",
    weightRu: "Около 1 кг за пару",
    location: "Either side of the heart, within the ribcage",
    locationRu: "По обе стороны от сердца, в грудной клетке",
    function: "Exchanges oxygen for carbon dioxide",
    functionRu: "Газообмен кислорода и углекислого газа",
    dailyFact: "Moves around 11,000 L of air",
    dailyFactRu: "Прокачивают около 11 000 л воздуха в день",
    medical: "Alveoli fold a tennis-court-sized exchange surface into the chest.",
    medicalRu: "Альвеолы умещают площадь размером с теннисный корт в грудную клетку.",
    bloodSupply: "Pulmonary and bronchial arteries",
    bloodSupplyRu: "Легочные и бронхиальные артерии",
    funFact: "The right lung carries three lobes and the left only two, leaving a notch for the heart.",
    funFactRu: "Правое легкое состоит из трех долей, а левое — из двух, оставляя место для сердца.",
    tissue: "Alveolar tissue",
    tissueRu: "Альвеолярная ткань",
    comparison: "Lungs vs. heart",
    comparisonRu: "Легкие против сердца",
    conditions: ["Asthma", "COPD", "Pneumonia", "Pulmonary embolism", "Pulmonary fibrosis", "Bronchitis", "Cystic fibrosis", "Lung cancer"],
    conditionsRu: ["Астма", "ХОБЛ", "Пневмония", "Тромбоэмболия легочной артерии", "Фиброз легких", "Бронхит", "Муковисцидоз", "Рак легких"],
    illustrated: true,
    hotspots: [
      { id: "trachea", label: "Trachea", labelRu: "Трахея", detail: "Carries air to the lungs", detailRu: "Проводит воздух к легким", position: [0, 1.6, 0.2], color: "#6393d8" },
      { id: "right-lung", label: "Right Lung", labelRu: "Правое легкое", detail: "Three lobes", detailRu: "Три доли", position: [-1.2, 0.1, 0.7], color: "#ee7c6a" },
      { id: "left-lung", label: "Left Lung", labelRu: "Левое легкое", detail: "Two lobes, room for the heart", detailRu: "Две доли, выемка под сердце", position: [1.2, 0.1, 0.7], color: "#f2a33b" },
      { id: "bronchus", label: "Bronchus", labelRu: "Бронх", detail: "Branching airway", detailRu: "Разветвленный дыхательный путь", position: [-0.03, 0.3, 0.35], color: "#d89bc4" },
      { id: "base", label: "Lung Base", labelRu: "Основание легкого", detail: "Rests on the diaphragm", detailRu: "Прилегает к диафрагме", position: [-1.14, -1.2, 1], color: "#7fa88a" },
    ],
  },
  {
    id: "liver",
    name: "Liver",
    nameRu: "Печень",
    scientificName: "Hepar",
    system: "Digestive System",
    systemRu: "Пищеварительная система",
    model: "/models/liver.glb",
    icon: "≈",
    accent: "#b86858",
    description: "A remarkable metabolic organ that filters blood, processes nutrients, and produces bile.",
    descriptionRu: "Уникальный метаболический орган, фильтрующий кровь, обрабатывающий питательные вещества и вырабатывающий желчь.",
    poetic: "The quiet alchemist",
    poeticRu: "Тихий алхимик",
    size: "About the size of a football",
    sizeRu: "Примерно с футбольный мяч",
    weight: "1.4–1.6 kg",
    weightRu: "1.4–1.6 кг",
    location: "Upper right abdomen",
    locationRu: "Правое верхнее подреберье",
    function: "Metabolism, detoxification & bile",
    functionRu: "Метаболизм, детоксикация и желчь",
    dailyFact: "Performs more than 500 functions",
    dailyFactRu: "Выполняет более 500 функций",
    medical: "It can regenerate a substantial portion of lost tissue.",
    medicalRu: "Печень способна регенерировать значительную часть утраченных тканей.",
    bloodSupply: "Hepatic artery and portal vein",
    bloodSupplyRu: "Печеночная артерия и воротная вена",
    funFact: "It is the only human organ that can regrow to full size from a fraction of itself.",
    funFactRu: "Это единственный орган человека, способный восстановиться до полного размера из небольшой части.",
    tissue: "Hepatic lobules",
    tissueRu: "Печеночные дольки",
    comparison: "Liver vs. intestine",
    comparisonRu: "Печень против кишечника",
    conditions: ["Fatty liver disease", "Hepatitis", "Cirrhosis", "Gallstones", "Haemochromatosis", "Liver cancer", "Autoimmune hepatitis", "Portal hypertension"],
    conditionsRu: ["Жировая болезнь печени", "Гепатит", "Цирроз", "Желчные камни", "Гемохроматоз", "Рак печени", "Аутоиммунный гепатит", "Портальная гипертензия"],
    illustrated: true,
    hotspots: [
      { id: "right-lobe", label: "Right Lobe", labelRu: "Правая доля", detail: "Largest hepatic lobe", detailRu: "Самая большая доля", position: [-0.75, 0.35, 0.75], color: "#ee7c6a" },
      { id: "left-lobe", label: "Left Lobe", labelRu: "Левая доля", detail: "Crosses the midline", detailRu: "Пересекает среднюю линию", position: [0.85, 0.25, 0.75], color: "#f2a33b" },
      { id: "portal", label: "Portal Vein", labelRu: "Воротная вена", detail: "Nutrient-rich inflow", detailRu: "Приток крови с питательными веществами", position: [0.1, -0.3, 0.82], color: "#6393d8" },
    ],
  },
  {
    id: "kidneys",
    name: "Kidneys",
    nameRu: "Почки",
    scientificName: "Renes",
    system: "Urinary System",
    systemRu: "Выделительная система",
    model: "/models/kidneys.glb",
    icon: "∞",
    accent: "#c96963",
    description: "Paired filtration organs that balance fluids, electrolytes, blood pressure, and waste removal.",
    descriptionRu: "Парные фильтрующие органы, балансирующие жидкость, электролиты, давление и вывод отходов.",
    poetic: "The master filters",
    poeticRu: "Мастера фильтрации",
    size: "Each is about a computer mouse",
    sizeRu: "Каждая размером с компьютерную мышь",
    weight: "120–170 g each",
    weightRu: "120–170 г каждая",
    location: "Either side of the spine below the ribs",
    locationRu: "По обе стороны от позвоночника ниже ребер",
    function: "Filters blood and forms urine",
    functionRu: "Фильтрация крови и образование мочи",
    dailyFact: "Filters roughly 180 L of fluid",
    dailyFactRu: "Фильтруют около 180 л жидкости в день",
    medical: "Nephrons fine-tune the chemistry of the bloodstream.",
    medicalRu: "Нефроны точно регулируют химический состав крови.",
    bloodSupply: "Renal arteries",
    bloodSupplyRu: "Почечные артерии",
    funFact: "They reclaim almost everything they filter — only about 1–2 L leaves the body as urine.",
    funFactRu: "Они возвращают почти все отфильтрованное — лишь 1–2 л выводятся в виде мочи.",
    tissue: "Renal cortex",
    tissueRu: "Корковое вещество почки",
    comparison: "Kidneys vs. liver",
    comparisonRu: "Почки против печени",
    conditions: ["Kidney stones", "Chronic kidney disease", "Urinary infection", "Glomerulonephritis", "Polycystic kidney disease", "Renal hypertension", "Acute kidney injury", "Nephrotic syndrome"],
    conditionsRu: ["Камни в почках", "Хроническая болезнь почек", "Инфекция мочевыводящих путей", "Гломерулонефрит", "Поликистоз почек", "Почечная гипертензия", "Острое повреждение почек", "Нефротический синдром"],
    illustrated: true,
    hotspots: [
      { id: "cortex", label: "Renal Cortex", labelRu: "Почечная кора", detail: "Outer filtering layer", detailRu: "Внешний фильтрующий слой", position: [-0.9, 0.55, 0.7], color: "#ee7c6a" },
      { id: "medulla", label: "Renal Medulla", labelRu: "Мозговое вещество", detail: "Concentrates urine", detailRu: "Концентрирует мочу", position: [0.85, 0.2, 0.7], color: "#f2a33b" },
      { id: "ureter", label: "Ureter", labelRu: "Мочеточник", detail: "Carries urine", detailRu: "Отводит мочу", position: [0.4, -1.1, 0.5], color: "#6393d8" },
    ],
  },
  {
    id: "eyeball",
    name: "Eye",
    nameRu: "Глаз",
    scientificName: "Oculus",
    system: "Sensory System",
    systemRu: "Сенсорная система",
    model: "/models/eyeball.glb",
    icon: "⊙",
    accent: "#7294b9",
    description: "A precision sensory organ that converts focused light into neural signals interpreted as vision.",
    descriptionRu: "Точнейший сенсорный орган, преобразующий сфокусированный свет в нервные импульсы зрения.",
    poetic: "A window made of light",
    poeticRu: "Окно из света",
    size: "About 24 mm across",
    sizeRu: "Около 24 мм в диаметре",
    weight: "Around 7.5 g",
    weightRu: "Около 7.5 г",
    location: "Within the bony orbit",
    locationRu: "В глазнице черепа",
    function: "Captures and focuses light",
    functionRu: "Захват и фокусировка света",
    dailyFact: "Makes thousands of tiny movements",
    dailyFactRu: "Делает тысячи микродвижений в день",
    medical: "The retina is an extension of the central nervous system.",
    medicalRu: "Сетчатка является продолжением центральной нервной системы.",
    bloodSupply: "Ophthalmic artery",
    bloodSupplyRu: "Глазная артерия",
    funFact: "The cornea carries no blood vessels at all; it takes oxygen directly from the air.",
    funFactRu: "Роговица вообще не содержит кровеносных сосудов и берет кислород напрямую из воздуха.",
    tissue: "Retinal layers",
    tissueRu: "Слои сетчатки",
    comparison: "Eye vs. brain",
    comparisonRu: "Глаз против мозга",
    conditions: ["Myopia", "Cataract", "Glaucoma", "Macular degeneration", "Retinal detachment", "Dry eye disease", "Astigmatism", "Conjunctivitis"],
    conditionsRu: ["Близорукость", "Катаракта", "Глаукома", "Макулодистрофия", "Отслоение сетчатки", "Синдром сухого глаза", "Астигматизм", "Конъюнктивит"],
    illustrated: true,
    hotspots: [
      { id: "cornea", label: "Cornea", labelRu: "Роговица", detail: "Clear focusing surface", detailRu: "Прозрачная фокусирующая поверхность", position: [-0.94, 0.05, 1.47], color: "#6393d8" },
      { id: "iris", label: "Iris", labelRu: "Радужка", detail: "Controls light entry", detailRu: "Регулирует приток света", position: [-1.22, -0.53, 1.15], color: "#f2a33b" },
      { id: "optic", label: "Optic Nerve", labelRu: "Зрительный нерв", detail: "Carries visual signals", detailRu: "Передает зрительные сигналы", position: [1.61, -0.18, 0.54], color: "#d89bc4" },
    ],
  },
  {
    id: "intestine",
    name: "Intestine",
    nameRu: "Кишечник",
    scientificName: "Intestinum",
    system: "Digestive System",
    systemRu: "Пищеварительная система",
    model: "/models/intestine.glb",
    icon: "§",
    accent: "#d78b77",
    description: "A folded digestive passage where nutrients are absorbed and the microbiome supports whole-body health.",
    descriptionRu: "Сложенный пищеварительный тракт, где всасываются питательные вещества и микробиом поддерживает здоровье.",
    poetic: "The inner garden",
    poeticRu: "Внутренний сад",
    size: "About 6–7 m when extended",
    sizeRu: "Около 6–7 м в длину",
    weight: "Varies with contents",
    weightRu: "Вариируется от содержимого",
    location: "Central and lower abdomen",
    locationRu: "Центральная и нижняя часть живота",
    function: "Digestion and nutrient absorption",
    functionRu: "Пищеварение и всасывание питательных веществ",
    dailyFact: "Hosts trillions of microorganisms",
    dailyFactRu: "Содержит триллионы микроорганизмов",
    medical: "Its surface is amplified by folds, villi, and microvilli.",
    medicalRu: "Поверхность увеличена складками, ворсинками и микроворсинками.",
    bloodSupply: "Superior and inferior mesenteric arteries",
    bloodSupplyRu: "Верхняя и нижняя брыжеечные артерии",
    funFact: "Its lining renews itself every few days — the fastest turnover of any tissue in the body.",
    funFactRu: "Слизистая обновляется каждые несколько дней — быстрее всех тканей организма.",
    tissue: "Intestinal villi",
    tissueRu: "Кишечные ворсинки",
    comparison: "Intestine vs. liver",
    comparisonRu: "Кишечник против печени",
    conditions: ["Irritable bowel syndrome", "Inflammatory bowel disease", "Celiac disease", "Diverticulitis", "Intestinal obstruction", "Colorectal polyps", "Crohn's disease", "Lactose intolerance"],
    conditionsRu: ["Синдром раздраженного кишечника", "Воспалительное заболевание кишечника", "Целиакия", "Дивертикулит", "Кишечная непроходимость", "Полипы толстой кишки", "Болезнь Крона", "Непереносимость лактозы"],
    illustrated: true,
    hotspots: [
      { id: "duodenum", label: "Duodenum", labelRu: "Двенадцатиперстная кишка", detail: "First small-intestine segment", detailRu: "Первый отдел тонкого кишечника", position: [0.6, 0.8, 0.75], color: "#f2a33b" },
      { id: "jejunum", label: "Jejunum", labelRu: "Тощая кишка", detail: "Major absorption region", detailRu: "Основной отдел всасывания", position: [-0.45, 0.1, 0.82], color: "#ee7c6a" },
      { id: "colon", label: "Colon", labelRu: "Толстая кишка", detail: "Reclaims water", detailRu: "Всасывает воду", position: [0.75, -0.55, 0.72], color: "#6393d8" },
    ],
  },
  {
    id: "pancreas",
    name: "Pancreas",
    nameRu: "Поджелудочная железа",
    scientificName: "Pancreas",
    system: "Endocrine System",
    systemRu: "Эндокринная система",
    model: "/models/pancreas.glb",
    icon: "◈",
    accent: "#c69a5e",
    description: "A dual-purpose gland that releases digestive enzymes into the gut and the hormones that steady blood sugar.",
    descriptionRu: "Железа двойного назначения, выделяющая ферменты в кишечник и гормоны для контроля сахара.",
    poetic: "The quiet regulator",
    poeticRu: "Тихий регулятор",
    size: "About 15 cm long",
    sizeRu: "Около 15 см в длину",
    weight: "70–100 g",
    weightRu: "70–100 г",
    location: "Behind the stomach, across the upper abdomen",
    locationRu: "За желудком, в верхней части живота",
    function: "Digestive enzymes and insulin",
    functionRu: "Пищеварительные ферменты и инсулин",
    dailyFact: "Makes about 1.5 L of enzyme-rich juice",
    dailyFactRu: "Вырабатывает около 1.5 л сока с ферментами в день",
    medical: "Islets of Langerhans release insulin and glucagon to balance blood sugar.",
    medicalRu: "Островки Лангерганса выделяют инсулин и глюкагон для регулирования сахара.",
    bloodSupply: "Splenic and pancreaticoduodenal arteries",
    bloodSupplyRu: "Селезеночная и панкреатодуоденальная артерии",
    funFact: "Barely 2% of it makes hormones; the rest is given over to digestive enzymes.",
    funFactRu: "Лишь 2% клеток вырабатывают гормоны; остальное занято пищеварительными ферментами.",
    tissue: "Pancreatic acini",
    tissueRu: "Ацинусы поджелудочной железы",
    comparison: "Pancreas vs. liver",
    comparisonRu: "Поджелудочная железа против печени",
    conditions: ["Pancreatitis", "Type 1 diabetes", "Pancreatic cancer", "Type 2 diabetes", "Exocrine insufficiency", "Pancreatic cysts", "Gallstone pancreatitis", "Insulinoma"],
    conditionsRu: ["Панкреатит", "Диабет 1 типа", "Рак поджелудочной железы", "Диабет 2 типа", "Внешнесекреторная недостаточность", "Кисты поджелудочной железы", "Желчнокаменный панкреатит", "Инсулинома"],
    illustrated: true,
    hotspots: [
      { id: "head", label: "Head", labelRu: "Головка", detail: "Cradled by the duodenum", detailRu: "Охвачена двенадцатиперстной кишкой", position: [-1.32, -0.36, 0.55], color: "#ee7c6a" },
      { id: "body", label: "Body", labelRu: "Тело", detail: "Crosses the spine", detailRu: "Пересекает позвоночник", position: [0.05, 0.25, 0.45], color: "#f2a33b" },
      { id: "tail", label: "Tail", labelRu: "Хвост", detail: "Reaches the spleen", detailRu: "Доходит до селезенки", position: [1.55, 0.3, 0.35], color: "#6393d8" },
      { id: "duct", label: "Pancreatic Duct", labelRu: "Проток поджелудочной железы", detail: "Drains enzymes to the gut", detailRu: "Отводит ферменты в кишечник", position: [-0.61, 0.39, 0.5], color: "#d89bc4" },
    ],
  },
  {
    id: "skin",
    name: "Skin",
    nameRu: "Кожа",
    scientificName: "Integumentum",
    system: "Integumentary System",
    systemRu: "Покровная система",
    model: "/models/skin.glb",
    icon: "▦",
    accent: "#c99277",
    description: "The body’s largest organ — a living barrier that senses touch, holds in water, and regulates temperature.",
    descriptionRu: "Крупнейший орган тела — живой барьер, ощущающий прикосновения, удерживающий воду и регулирующий температуру.",
    poetic: "The living boundary",
    poeticRu: "Живая граница",
    size: "About 2 m² spread flat",
    sizeRu: "Около 2 м² площади",
    weight: "3.5–5 kg",
    weightRu: "3.5–5 кг",
    location: "Covering the entire body",
    locationRu: "Покрывает все тело",
    function: "Protects, senses, and cools",
    functionRu: "Защита, чувствительность и терморегуляция",
    dailyFact: "Sheds around 500 million cells",
    dailyFactRu: "Сбрасывает около 500 миллионов клеток в день",
    medical: "Three layers — epidermis, dermis, and hypodermis — each with a distinct job.",
    medicalRu: "Три слоя — эпидермис, дерма и гиподерма — каждый со своей функцией.",
    bloodSupply: "Dermal vascular plexus",
    bloodSupplyRu: "Кожное сосудистое сплетение",
    funFact: "A single square centimetre can hold hundreds of sweat glands and metres of blood vessels.",
    funFactRu: "Один квадратный сантиметр может содержать сотни потовых желез и метры сосудов.",
    tissue: "Epidermal layers",
    tissueRu: "Слои эпидермиса",
    comparison: "Skin vs. intestine",
    comparisonRu: "Кожа против кишечника",
    conditions: ["Eczema", "Psoriasis", "Melanoma", "Acne vulgaris", "Cellulitis", "Contact dermatitis", "Rosacea", "Vitiligo"],
    conditionsRu: ["Экзема", "Псориаз", "Меланома", "Акне", "Целлюлит", "Контактный дерматит", "Розацеа", "Витилиго"],
    illustrated: true,
    hotspots: [
      { id: "epidermis", label: "Epidermis", labelRu: "Эпидермис", detail: "Outer protective layer", detailRu: "Внешний защитный слой", position: [-0.05, 0.88, 1.4], color: "#ee7c6a" },
      { id: "dermis", label: "Dermis", labelRu: "Дерма", detail: "Nerves, vessels & glands", detailRu: "Нервы, сосуды и железы", position: [0.29, 0.05, 1.4], color: "#f2a33b" },
      { id: "hypodermis", label: "Hypodermis", labelRu: "Гиподерма", detail: "Fat and insulation", detailRu: "Жир и термоизоляция", position: [-0.39, -1.15, 1.4], color: "#6393d8" },
      { id: "follicle", label: "Hair Follicle", labelRu: "Волосяной фолликул", detail: "Anchors each hair", detailRu: "Удерживает волос", position: [0.89, -0.44, 1.4], color: "#d89bc4" },
    ],
  },
];

export const organById = Object.fromEntries(organs.map((organ) => [organ.id, organ])) as Record<OrganId, Organ>;

export function getLocalizedOrgan(organ: Organ, lang: Language = "en"): Organ {
  if (lang === "ru") {
    return {
      ...organ,
      name: organ.nameRu || organ.name,
      system: organ.systemRu || organ.system,
      description: organ.descriptionRu || organ.description,
      poetic: organ.poeticRu || organ.poetic,
      size: organ.sizeRu || organ.size,
      weight: organ.weightRu || organ.weight,
      location: organ.locationRu || organ.location,
      function: organ.functionRu || organ.function,
      dailyFact: organ.dailyFactRu || organ.dailyFact,
      medical: organ.medicalRu || organ.medical,
      bloodSupply: organ.bloodSupplyRu || organ.bloodSupply,
      funFact: organ.funFactRu || organ.funFact,
      tissue: organ.tissueRu || organ.tissue,
      comparison: organ.comparisonRu || organ.comparison,
      conditions: organ.conditionsRu || organ.conditions,
      hotspots: organ.hotspots.map((h) => ({
        ...h,
        label: h.labelRu || h.label,
        detail: h.detailRu || h.detail,
      })),
    };
  }
  return organ;
}
